# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
    ]
