# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 17:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_auto_20180323_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quotes',
            managers=[
                ('quotesobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
